version: 2

jobs:
  steps:
    - checkout
    - run:
        name: Installing Dependencies
        command: 'yarn install'
    - run:
        name: Build Client
        command: 'yarn build:client'
    - run:
        name: Starting Servers
        command: 'yarn production'
